{% set name = "optuna-integration" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 86201502fab9c3bba8aa6ffaac0f465b0bcdb75ec75fd157eda8b96352fb3cf3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=61.1.0
    - pip
  run:
    - python >=3.6
    - optuna

test:
  imports:
    - optuna_integration
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://optuna.org/
  summary: An integration module of Optuna
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://optuna-integration.readthedocs.io
  dev_url: https://github.com/optuna/optuna-integration

extra:
  recipe-maintainers:
    - y0z
    - eukaryo
    - nabenabe0928
    - HideakiImamura
    - c-bata
    - contramundum53
    - gen740
    - knshnb
    - not522
    - toshihikoyanase
