{% set name = "optuna-integration" %}
{% set version = "4.3.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3f7038f3cba84f00e9229078f0ea8dca8983fa2079e1d0457d5082d034829ff9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.1.0
    - pip
  run:
    - python >={{ python_min }}
    - optuna

test:
  imports:
    - optuna_integration
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://optuna.org/
  summary: An integration module of Optuna
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://optuna-integration.readthedocs.io
  dev_url: https://github.com/optuna/optuna-integration

extra:
  recipe-maintainers:
    - y0z
    - eukaryo
    - nabenabe0928
    - HideakiImamura
    - c-bata
    - contramundum53
    - gen740
    - knshnb
    - not522
    - toshihikoyanase
